# Generated by Django 3.2.16 on 2022-12-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20221213_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='base.author'),
        ),
    ]
