# Generated by Django 3.2.16 on 2022-12-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20221213_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='Article', to='base.Author'),
        ),
    ]
